{{- if .Values.browserless.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshrimp.browserlessFullname" . }}
  labels:
    {{- include "openshrimp.labels" . | nindent 4 }}
    {{- include "openshrimp.browserlessSelectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.browserless.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openshrimp.browserlessSelectorLabels" . | nindent 4 }}
{{- end }}
