{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshrimp.frontendFullname" . }}
  labels:
    {{- include "openshrimp.labels" . | nindent 4 }}
    {{- include "openshrimp.frontendSelectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openshrimp.frontendSelectorLabels" . | nindent 4 }}
{{- end }}
