{{- if .Values.pgvector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshrimp.pgvectorFullname" . }}
  labels:
    {{- include "openshrimp.labels" . | nindent 4 }}
    {{- include "openshrimp.pgvectorSelectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.pgvector.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "openshrimp.pgvectorSelectorLabels" . | nindent 4 }}
{{- end }}
