{{- if and .Values.pgvector.enabled .Values.pgvector.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openshrimp.pgvectorFullname" . }}-data
  labels:
    {{- include "openshrimp.labels" . | nindent 4 }}
    {{- include "openshrimp.pgvectorSelectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pgvector.persistence.size }}
  {{- if .Values.pgvector.persistence.storageClassName }}
  storageClassName: {{ .Values.pgvector.persistence.storageClassName }}
  {{- end }}
{{- end }}
